### ISSUE TITLE
gopls linter doesn't work unless .git folder present in module root 

### ISSUE THREAD

**Issue by alexryndin** [dense-analysis/ale#2795] opened 2019-09-28 22:09 UTC
## Information

**VIM version**

Tested with:
NVIM v0.4.2
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  3 2019 19:23:34)

Operating System: Arch Linux

## What went wrong

It seems like gopls linters doesn't work when there is no `.git` directory (even empty) in the project or source codes directory root. For instance, open some `main.go` in some directory under `$GOPATH` containing some errors - ale shows nothing. Then do `mkdir .git` and open main.go again - now ale show errors properly. This is not gopls error for sure since `gopls check` show error in cli.

## Reproducing the bug

1. Create directory test under `$GOPATH`. 
2. Create `main.go` in the directory, created in step 1.
3. Insert some errors containing code there. 

### :ALEInfo

 Current Filetype: go
Available Linters: ['bingo', 'gobuild', 'gofmt', 'golangci-lint', 'golint', 'gometalinter', 'gopls', 'gosimple', 'gotype', 'govet', 'golangserver', 'staticcheck']
   Linter Aliases:
'gobuild' -> ['go build']
'govet' -> ['go vet']
  Enabled Linters: ['gopls']
 Suggested Fixers: 
  'gofmt' - Fix Go files with go fmt.
  'goimports' - Fix Go files imports with goimports.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_go_go_executable = 'go'
let g:ale_go_golangci_lint_executable = 'golangci-lint'
let g:ale_go_golangci_lint_options = '--enable-all'
let g:ale_go_golangci_lint_package = 0
let g:ale_go_gopls_executable = 'gopls'
let g:ale_go_gopls_options = '--mode stdio'
let g:ale_go_langserver_executable = 'go-langserver'
let g:ale_go_langserver_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['gopls']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

**Comment by alexryndin** [comment] 2019-09-28 22:26
I'm not a good vimscripter, but it seems like something is wrong with FindProjectRoot function https://github.com/dense-analysis/ale/blob/3ae01ba24967a37e5a41626673422be53e188026/ale_linters/go/gopls.vim#L25

**Comment by hsanson** [comment] 2019-10-01 13:08
This is a recurrent problem with Language Servers in ALE. Each language server must define a root directory or it won't start. The problem is that there is no reliable way to determine what the root directory is from the currently open buffer (see #2790, #2699).

You may try to use g:ale_lsp_root to force a root directory for Go project (e.g. GOPATH) or make sure you have a .git directory in the root path.

**Comment by w0rp** [comment] 2019-10-04 09:26
For Go projects, there may be some configuration file for a project we can look for to detect the project root by default.

This isn't a bug, this is just the best we can do for detecting the project root so far.

**Comment by maxbrunet** [comment] 2021-07-03 23:42
@w0rp could we use the current working directory instead of an empty string in last resort?

It may be wrong, but a least the server will start. Chances are that it will be valid as `GOPATH` is deprecated and a formal project would have `go.mod` file (already handled by the plugin), the user may only be writing a quick snippet of code in the middle of nowhere.

**Comment by hsanson** [comment] 2021-07-04 11:13
This has been raised and discussed before. Starting language servers on the working directory can result in ALS spawning new language server processes for every single file that is opened in vim.  I already experienced this with java language server and as you can imagine my machine ran out of memory quickly and died.

**Comment by hsanson** [comment] 2021-08-03 13:55
Closing since works as expected and little ALE can do in terms of finding Go projects root directory automatically.

**Closed by hsanson** 2021-08-03 13:55 UTC
Labels: enhancement
