### ISSUE TITLE
govet linter broken with Go 1.13

### ISSUE THREAD

**Issue by majewsky** [dense-analysis/ale#2761] opened 2019-09-10 12:01 UTC
In Go 1.12.9, govet reports errors like this (excerpt from `ALEInfo`):

```
(executable check - success) go
(finished - exit code 2) ['/bin/zsh', '-c', 'cd ''/x/src/github.com/sapcc/keppel/internal/api/keppel'' &&  go vet  .']
<<<OUTPUT STARTS>>>
# github.com/sapcc/keppel/internal/api/keppel [github.com/sapcc/keppel/internal/api/keppel.test]
./accounts_test.go:45:8: not enough arguments in call to NewAPI
        have (keppel.AuthDriver, keppel.NameClaimDriver, *keppel.DB)
        want (keppel.AuthDriver, keppel.NameClaimDriver, *keppel.DB, keppel.Auditor)
<<<OUTPUT ENDS>>>
```

This works fine with latest ALE (tested with https://github.com/dense-analysis/ale/commit/6e18c03d80c323e740f87103fc05955b5c61b54e). However, in Go 1.13, I don't get a mark for this error in the UI. The output now looks like this:

```
(executable check - success) go
(finished - exit code 2) ['/bin/zsh', '-c', 'cd ''/x/src/github.com/sapcc/keppel/internal/api/keppel'' &&  go vet  .']
<<<OUTPUT STARTS>>>
# github.com/sapcc/keppel/internal/api/keppel
vet: ./accounts_test.go:45:20: too few arguments in call to NewAPI
<<<OUTPUT ENDS>>>
```

I suspect that the issue is that `go vet` started prefixing its error messages with `vet: `.

**Comment by mrvik** [comment] 2019-09-15 11:45
Same issue here with `go version go1.13 linux/amd64`

**Comment by rsheasby** [comment] 2019-09-18 12:11
I'm having the exact same issue. Can confirm the issue is the `vet: ` in front of the output. Changing the go binary to a shell script that trims the `vet: ` from output works perfectly. Should be a quick fix, but I can't for the life of me figure out where the output parsing occurs. The source code is a maze

**Comment by doesnotcommit** [comment] 2019-09-19 15:36
fwiw, `go vet` output parsing occurs here: https://github.com/dense-analysis/ale/blob/61cfb3fefb0ebd8654be452046bd2ba24025311f/autoload/ale/handlers/go.vim#L11

**Comment by aj3423** [comment] 2019-10-13 15:18
Same problem here,  is there any quick workaround for now ?

**Comment by majewsky** [comment] 2019-10-13 19:30
You can apply this patch to your local copy of ale:
```patch
diff --git a/autoload/ale/handlers/go.vim b/autoload/ale/handlers/go.vim
index f17cd86211..29091fdeb3 100644
--- a/autoload/ale/handlers/go.vim
+++ b/autoload/ale/handlers/go.vim
@@ -8,7 +8,7 @@
 " Description: moved to generic Golang file from govet
 
 function! ale#handlers#go#Handler(buffer, lines) abort
-    let l:pattern = '\v^([a-zA-Z]?:?[^:]+):(\d+):?(\d+)?:? ?(.+)$'
+    let l:pattern = '\v^%(vet:\s*)?([a-zA-Z]?:?[^:]+):(\d+):?(\d+)?:? ?(.+)$'
     let l:output = []
     let l:dir = expand('#' . a:buffer . ':p:h')
 
```

**Comment by aj3423** [comment] 2019-10-16 16:03
> You can apply this patch to your local copy of ale:
> 
>  function! ale#handlers#go#Handler(buffer, lines) abort
> -    let l:pattern = '\v^([a-zA-Z]?:?[^:]+):(\d+):?(\d+)?:? ?(.+)$'
> +    let l:pattern = '\v^%(vet:\s*)?([a-zA-Z]?:?[^:]+):(\d+):?(\d+)?:? ?(.+)$'

For Windows it's `'vet.exe:...`

    let l:pattern = '\v^%(vet.exe:\s*)?([a-zA-Z]?:?[^:]+):(\d+):?(\d+)?:? ?(.+)$'

**Comment by w0rp** [comment] 2019-10-16 16:16
There's an existing pull request, but someone just needs to apply a patch like patches mentioned above with tests.

**Comment by RandomCivil** [comment] 2020-03-25 05:17
this issue has been fixed?

**Comment by arthurk** [comment] 2020-04-09 13:00
not fixed yet, issue still happening with go 1.14

**Comment by kolanos** [comment] 2020-07-25 01:53
Can we get @mostfunkyduck's PR merged? This seems like a discreet fix that is likely affecting a lot of ALE users.

**Closed** 2020-08-07 07:54 UTC
Labels: bug

**Comment by w0rp** [comment] 2020-08-07 07:55
I've merged that PR now, so it should work.
