### ISSUE TITLE
Custom linter not running "immediately"

### ISSUE THREAD

**Issue by rolfschr** [dense-analysis/ale#3444] opened 2020-11-18 23:08 UTC
Hi,

I followed #1405 and was able to implement a custom linter. I do get the expected error messages when saving the file. I do not get them "immediately" (i.e. during typing, on insert leave, etc.). However, within the same (n)vim session, I experience this behavior for other file types. In my case, I added a new json linter which only seems to be triggered on save but editing python/bash files triggers linting (flake8/shellcheck) immediately. Is there anything I could do wrong for my own linter?
Thanks!

ALEInfo says
```
let g:ale_lint_on_enter = 1                                                                                                                                                                                        
let g:ale_lint_on_filetype_changed = 1                                                                                                                                                                             
let g:ale_lint_on_insert_leave = 1                                                                                                                                                                                 
let g:ale_lint_on_save = 1                                                                                                                                                                                         
let g:ale_lint_on_text_changed = 'normal'    
```

**Comment by w0rp** [comment] 2020-11-21 16:23
You've probably set `lint_file` for that linter to `1`, so set it to `0`. Share your linter configuration so others can see it.

**Comment by w0rp** [comment] 2020-11-21 16:23
I'll close this as it's not a bug or feature.

**Closed by w0rp** 2020-11-21 16:23 UTC

**Comment by rolfschr** [comment] 2020-11-23 08:46
Hi, 
thanks for the quick reply. My linter is copied & adapted from json/jsonlint. It is named ``jsoncfg`` and it "works" as I said. Just not during text change. Other linters do that so I feel something is wrong with the specific linter.

```
call ale#Set('json_jsoncfg_executable', '/home/rolfschr/src/linter/linter.py')                                                                                                                                     
                                                                                                                                                                                                                   
function! ale_linters#json#jsoncfg#GetExecutable(buffer) abort                                                                                                                                                     
    let l:executable = ale#Var(a:buffer, 'json_jsoncfg_executable')                                                                                                                                                
    return executable                                                                                                                                                                                              
endfunction                                                                                                                                                                                                        
                                                                                                                                                                                                                   
function! ale_linters#json#jsoncfg#GetCommand(buffer) abort                                                                                                                                                        
    let l:executable = ale_linters#json#jsoncfg#GetExecutable(a:buffer)                                                                                                                                            
    " let l:executable = ale#Var(a:buffer, 'json_jsoncfg_executable')                                                                                                                                              
    return ale#node#Executable(a:buffer, l:executable)                                                                                                                                                             
endfunction                                                                                                                                                                                                        
                                                                                                                                                                                                                   
function! ale_linters#json#jsoncfg#Handle(buffer, lines) abort                                                                                                                                                     
    " Matches patterns like the following:                                                                                                                                                                         
    " line 2, col 15, found: 'STRING' - expected: 'EOF', '}', ',', ']'.                                                                                                                                            
    let l:pattern = '^\(\d\+\),\(\d*\): \(.\+\)$'                                                                                                                                                                  
    let l:output = []                                                                                                                                                                                              
                                                                                                                                                                                                                   
    for l:match in ale#util#GetMatches(a:lines, l:pattern)                                                                                                                                                         
        call add(l:output, {                                                                                                                                                                                       
        \   'lnum': l:match[1] + 0,                                                                                                                                                                                
        \   'col': l:match[2] + 0,                                                                                                                                                                                 
        \   'text': l:match[3],                                                                                                                                                                                    
        \})                                                                                                                                                                                                        
    endfor                                                                                                                                                                                                         
                                                                                                                                                                                                                   
    return l:output                                                                                                                                                                                                
endfunction                                                                                                                                                                                                        
                                                                                                                                                                                                                   
call ale#linter#Define('json', {                                                                                                                                                                                   
\   'name': 'jsoncfg',                                                                                                                                                                                             
\   'executable': function('ale_linters#json#jsoncfg#GetExecutable'),                                                                                                                                              
\   'output_stream': 'stdout',                                                                                                                                                                                     
\   'lint_file': 0,                                                                                                                                                                                                
\   'command': function('ale_linters#json#jsoncfg#GetCommand'),                                                                                                                                                    
\   'callback': 'ale_linters#json#jsoncfg#Handle',                                                                                                                                                                 
\})    
```

I did not set the ``lint_file`` option previously and added it now. Event when setting it to ``0``, the linter still only lints on save, not on text change. Running ``ALELint`` on the unsaved buffer also does not update the warn/err message so I guess your assumption is pointing to the right direction: The linter only seems to lint the saved file. My ALE config is "borring" I think:

```
let g:ale_fixers = {                                                                                                                                                                                               
\  'haskell': ['hlint'],                                                                                                                                                                                           
\  'python': ['black', 'isort'],                                                                                                                                                                                   
\  'perl': ['perltidy'],                                                                                                                                                                                           
\  'nix': ['nixpkgs-fmt'],                                                                                                                                                                                         
\}                                                                                                                                                                                                                 
let g:ale_linters = {                                                                                                                                                                                              
\  'zsh': ['shell', 'shellcheck'],                                                                                                                                                                                 
\}                                                                                                                                                                                                                 
let g:ale_python_black_options = '--line-length 100'                                                                                                                                                               
let g:ale_python_flake8_options = '--max-line-length=100'                                                                                                                                                          
let g:ale_fix_on_save = 1                                                                                                                                                                                          
let g:ale_perl_perltidy_options = '-l=100 -pt=2 -sbt=2 -bt=2 -bbt=2'                                                                                                                                               
let g:ale_nix_nixpkgsfmt_executable = 'nixfmt' 
```
Is there something else I could try?

**Comment by rolfschr** [comment] 2020-11-26 06:03
Hi,

I have to apologize. The linter did not correctly read from stdin! Everthing works as expected, sorry for the inconvenience.
