### ISSUE TITLE
Message "Press ENTER or type command to continue" for hlint appears since b3d1d6eecfb5eb08787501294979dc6ba2426c35

### ISSUE THREAD

**Issue by RST-J** [dense-analysis/ale#4141] opened 2022-04-03 20:28 UTC
Hello,
first, please let me now details I missed to add here, if the problem is not obviously caused by the suspected change.

I recently updated ale (by pulling master) and since then observed that errors reported by hlint behave differently than before.
Now, if hlint reports an error, neovim displays the "Press ENTER or type command to continue" message beneath the hlint output in the status bar(? not sure what its called exactly, sorry).
This repeats when I navigate left and right in the identified line and certain commands do not work unless I hit enter but then message immediately reappears.

I tracked this behavior down to be introduced (in my setup at least) by this commit: https://github.com/dense-analysis/ale/commit/b3d1d6eecfb5eb08787501294979dc6ba2426c35

As I do not now anything substantial about vim plugins, I cannot judge whether this is only due to this change or must have to do with my other plugins and or some config. Can someone tell me?

Edit: I am using neovim v0.7.0-dev from the PPA on Kubuntu 20.04.4. Also using vim-airline as a plugin (amongst 32 others which I'd less suspect of being a potential interference).

**Comment by taq** [comment] 2022-04-04 14:20
I can confirm that. Even moving left or right on a warning/error line fires the message and the ENTER key request. The ENTER request must be removed.

**Comment by taq** [comment] 2022-04-04 20:26
> Hello, first, please let me now details I missed to add here, if the problem is not obviously caused by the suspected change.
> 
> I recently updated ale (by pulling master) and since then observed that errors reported by hlint behave differently than before. Now, if hlint reports an error, neovim displays the "Press ENTER or type command to continue" message beneath the hlint output in the status bar(? not sure what its called exactly, sorry). This repeats when I navigate left and right in the identified line and certain commands do not work unless I hit enter but then message immediately reappears.
> 
> I tracked this behavior down to be introduced (in my setup at least) by this commit: [b3d1d6e](https://github.com/dense-analysis/ale/commit/b3d1d6eecfb5eb08787501294979dc6ba2426c35)
> 
> As I do not now anything substantial about vim plugins, I cannot judge whether this is only due to this change or must have to do with my other plugins and or some config. Can someone tell me?
> 
> Edit: I am using neovim v0.7.0-dev from the PPA on Kubuntu 20.04.4. Also using vim-airline as a plugin (amongst 32 others which I'd less suspect of being a potential interference).

Based on that commit, seems that there's some newline chars still present. I saw the 
```vimscript
let l:message = substitute(l:message, "\n", '', 'g')
```
there, but if you use `echon` without a newline, it just prints the message on script, but with a newline it shows the "Press ENTER ..." message.

Would be cool also to use virtual text, when available. :-)

**Comment by hsanson** [comment] 2022-04-05 10:04
Managed to reproduce the issue thanks to @RazorBest comment and created a fix #4144 that reverts the change in #3888 that caused the issue.

Those affected please check if the fix works and does not break anything else. If I get positive feedback I will merge this since is affecting many users.

**Comment by taq** [comment] 2022-04-05 12:59
Seems fixed to me.

**Comment by taq** [comment] 2022-04-05 13:11
Uh-oh, on long messages, ENTER request still remains.

**Comment by royhamulak** [comment] 2022-04-05 20:47
Any update on this? this is driving me nuts 😭

**Comment by hsanson** [comment] 2022-04-06 01:53
@taq I have merged my fix since this is affecting many and seems to solve it for some.  Can you please check again with master branch and report if you still see the problem?

**Comment by taq** [comment] 2022-04-06 11:07
@hsanson thanks! I didn't find yet another long message, but I'll tell you if everything is fine. Just updated to master now.

**Closed** 2022-04-06 11:29 UTC
