### ISSUE TITLE
Quickfix overwritting

### ISSUE THREAD

**Issue by GGCristo** [dense-analysis/ale#3457] opened 2020-11-23 16:28 UTC
3 years ago this question was asked: (https://www.reddit.com/r/vim/comments/7c5f1a/two_plugins_writing_to_quickfixloc_list_at_the/).
I was in a similar situation, I managed to have a workaround, but a workaround it's a workaround and I don't know if it covers all the edge cases.
This is all the info I could find about this feature (https://groups.google.com/u/2/g/vim_dev/c/Cd1sNBzc0NE).
Do you think it's worth in work on it? Or should vim/Neovim work in a better API?
Edit: I find a plugins that uses this feature, I hope this can help:
https://github.com/yegappan/grep/blob/78d13a05f46c400726a8494217d84191392cca95/autoload/grep.vim#L447

**Comment by GGCristo** [comment] 2021-03-29 11:13
Re-reading this give me the impression I am not explaining myself with enough clarity, the idea is that ALE ask for a free quickfix get the id of that quickfix and only work with that quickfix. It would be very handy to also take advantage and create shortcuts related to that quickfix like ``ALEOpenQuickfix`` .

**Comment by w0rp** [comment] 2023-02-03 09:10
Will consider months from now.

**Comment by w0rp** [comment] 2023-09-08 00:38
This is a duplicate of #1140, after reading through both. I'll try to get that done for the milestone.

**Closed by w0rp** 2023-09-08 00:38 UTC
Labels: enhancement
