### ISSUE TITLE
neovim highlight problem happened again,after the last update

### ISSUE THREAD

**Issue by chenjie199234** [dense-analysis/ale#2763] opened 2019-09-11 02:41 UTC
PC:win10 1903
edit:Neovim 0.3.8
this problem happened before,and finally these related codes were removed from the master.
were these codes merged into the master again?
i updated the ale and it happened again.
![企业微信截图_15681694818763](https://user-images.githubusercontent.com/29348971/64664087-a0315200-d480-11e9-94ff-8f4cea16208e.png)

**Comment by tomarrell** [comment] 2019-09-11 08:23
This is a duplicate of #2760. 

The current solution is to checkout to the commit prior to the highlight API PR merge: 73812c3e41c1c7fcf1705811f35ac4c9ccec003e

**Comment by w0rp** [comment] 2019-09-11 15:53
Pull again. I fixed it by ignoring all errors from that function.

**Closed by w0rp** 2019-09-11 15:53 UTC
