### ISSUE TITLE
Flow 0.66 changed the error messages format

### ISSUE THREAD

**Issue by ahmedelgabri** [dense-analysis/ale#1398] opened 2018-03-05 19:46 UTC
Flow 0.66 changed the error messages format [more here](https://medium.com/flow-type/better-flow-error-messages-for-the-javascript-ecosystem-73b6da948ae2) which now makes ale messages not very useful

**Comment by w0rp** [comment] 2018-03-06 14:59
The changelog claims that existing plugins should continue to work, until you pass a flag to use the new JSON format.

**Comment by ahmedelgabri** [comment] 2018-03-06 15:13
But that's not the case when I see the errors from ale here is my ale [config](https://github.com/ahmedelgabri/dotfiles/blob/master/vim/.vim/after/plugin/ale.vim) & this is an example:

**Flow `0.53.1`**

<img width="1005" alt="flow 0 53 1" src="https://user-images.githubusercontent.com/63876/37039997-1bc955e8-2159-11e8-9cf1-99795e334334.png">

**Flow `0.66`**

<img width="1003" alt="flow 0 66" src="https://user-images.githubusercontent.com/63876/37040018-26b3fcba-2159-11e8-976b-9eae1bac8a96.png">

**Comment by w0rp** [comment] 2018-03-07 12:20
Sounds like they fucked up, then. I might have a look when I get the time, or someone else can create a pull request for it. I believe some version detection is already down for the linter, so it shouldn't be too hard to fix.

**Comment by ahmedelgabri** [comment] 2018-03-07 12:46
@TrySound the error messages are not complete, if you check he article I linked to flow now with have something like footnotes or markers. And they are not always going be shown in full now, here is an example, check the second error. It's not as clear & maybe even gets cut off now

<img src="https://cdn-images-1.medium.com/max/2000/1*BAYW1TlbDM9VhVYCoo2azQ.jpeg" >

**Comment by TrySound** [comment] 2018-03-07 12:49
I'd say before they weren't full too

**Comment by ahmedelgabri** [comment] 2018-03-07 12:52
Ok, then maybe I'm missing something. But after the flow update some messages didn't seem to make much sense, I'll keep an eye on it again & see.

**Comment by loyd** [comment] 2018-03-20 08:47
Also `ALEDetail` is useless now:
```
References: [1] [2]
```

**Comment by w0rp** [comment] 2018-03-20 12:54
Feel free to submit a pull request to fix it.

**Comment by choonkending** [comment] 2018-05-13 12:13
Ale newbie here. 

Is there any chance we could try to format the error message output by ale to be multiline and as descriptive as command line (My error messages appear in 1 long line now, and they can be difficult to read)? 

I tried taking a look at https://github.com/w0rp/ale/blob/master/ale_linters/javascript/flow.vim#L160 and got lost pretty quickly. Happy to take a stab at contributing if you have any ideas in mind.

**Comment by ahmedelgabri** [comment] 2018-05-13 16:08
If you want to show multiline you can try `set cmdheight=<number>` but I won't do this y default or even add it to the plugin to be honest.

**Comment by choonkending** [comment] 2018-05-13 23:51
@ahmedelgabri thanks for that suggestion! 👼 

I thought about this further, I think what I'm hoping for is to be able to see something like below somehow within vim, either by using `lopen` or by using `ALEDetails`. Is it possible? Currently my error message gets appended in 1 long line. 

![image](https://user-images.githubusercontent.com/3787885/39972946-dfc25908-575b-11e8-8ab7-45a534ee170c.png)

Maybe I'm missing something?

**Comment by w0rp** [comment] 2018-06-20 22:10
If you set a `'detail'` key for the loclist items with multiple lines, you can view the multi-line message in a window with `:ALEDetail`. I just realised that particular loclist key wasn't documented, so I updated the documentation.

**Comment by joeybaker** [comment] 2018-06-20 22:13
@w0rp Thanks for the work-around! After reading through the docs you just added, I'm a little confused. What should `detail` should be set to?

**Comment by w0rp** [comment] 2018-06-20 23:01
Someone can modify the `flow` linter file in ALE to set detail to a multi-line string with a more descriptive message. If anyone knows how to build such a string from flow's JSON output, create a pull request for it. I don't know much about flow.

**Comment by sdeleon28** [comment] 2019-08-22 22:22
I think the problem is not related to how the loclist is configured but rather to some parts of the Flow output being ignored.

This is how the JSON returned by Flow looks:

```
{
  "flowVersion":"0.87.0",
  "jsonVersion":"1",
  "errors":[
    {
      "kind":"infer",
      "level":"error",
      "suppressions":[],
      "extra":[
        {
          "message":[
            {
              "context":null,
              "descr":"References:",
              "type":"Blame",
              "path":"",
              "line":0,
              "endline":0,
              "start":1,
              "end":0
            }
          ]
        },
        {
          "message":[
            {
              "context":"export type MyRecord = RecordOf<Props>;",
              "descr":"[1]",
              "type":"Blame",
              "loc":{
                "source":"/blah/types.js",
                "type":"SourceFile",
                "start":{"line":217,"column":44,"offset":5098},
                "end":{"line":217,"column":67,"offset":5122}
              },
              "path":"/blah/types.js",
              "line":217,
              "endline":217,
              "start":44,
              "end":67
            }
          ]
        }
      ],
      "message":[
        {
          "context":"        return !!(product && product.get && product.get('isGroup'));",
          "descr":"Cannot call `product.get` because: Either property `isGroup` is missing in `Props` [1] in type argument `K`. Or property `isGroup` is missing in `Props` [1] in type argument `K`.",
          "type":"Blame",
          "loc":{
            "source":"/blah/selectors.js",
            "type":"SourceFile",
            "start":{"line":176,"column":53,"offset":7087},
            "end":{"line":176,"column":55,"offset":7090}
          },
          "path":"/blah/selectors.js",
          "line":176,
          "endline":176,
          "start":53,
          "end":55
        }
      ]
    },
}
```

What's missing from the error message is what's under the `extra` key. The missing flow output should look like this:

```
     blah/types.js
 [1] 217│ export type MyRecord = RecordOf<Props>;
```

Unfortunately I don't really understand how `ale_linters#javascript#flow#Handle` is being called or why it's only being passed the `message` key. It it were passed the entire JSON for the error, then some logic could be implemented inside the method to include those references at the bottom of the output.

**Comment by sdeleon28** [comment] 2019-08-22 23:40
I've added a temporary fix for this in #2725.

This only works for the `flow` linter. `flow-language-server` seems to have the same problem.

**Comment by hsanson** [comment] 2021-08-03 15:39
Related: #2649

**Comment by hsanson** [comment] 2022-12-10 03:13
Flow is deprecated #3859 #2649

**Closed by hsanson** 2022-12-10 03:13 UTC
Labels: bug
