### ISSUE TITLE
Add option/command to show errors across multiple files

### ISSUE THREAD

**Issue by jakemco** [dense-analysis/ale#2129] opened 2018-12-06 23:16 UTC
Right now, as far as I can tell, ALE is filtering the errors/messages returned from the linter/LSP by the current file I have open. ie: If I have two files A and B that both have lint errors in them, and I have file A open, it will only show me the issues for file A. (That said, I don't know enough about the internals of ALE/LSP, this could be happening at the LSP level instead? But I vaguely recall this also being the case for non-LSP linters).

While most of the time this is nice (because then you're not overwhelmed when there are many issues across the project), it would be nice to have an option or a separate command that fills the location list with the errors from all files in the project. For me, it's sometimes nice to make a change in one place, see all the type errors (for example) that ripple out from there, and then just go through them one by one cleaning up. With the current way that ALE works, I have to run the typechecker in a separate window and manually go back and forth, rerunning the typechecker every time. If ALE had a "show me all the errors" option, I could load them all into my location list and just keep on doing :lnext or :ALENext until everything is fixed.

(this looks similar to #1241, but I felt the request was slightly different; feel free to merge if that seems appropriate)

**Comment by RyanSquared** [comment] 2018-12-07 16:47
I feel like this could be an option _on top of_ #1241. However, isn't the loclist intentionally local to the current buffer/view? Perhaps a different mechanism for showing _all_ errors would be useful.

**Comment by w0rp** [comment] 2018-12-07 17:19
This may be either difficult or impossible for LSP. It sends us diagnostics for files, and those results are mapped to files you have open. What would make more sense is collecting everything into one list, maybe in quickfix. quickfix is overused by too many different things, though.

**Comment by nelsyeung** [comment] 2021-01-23 09:32
Just want to say I'd love this feature too. This is something that VS Code has. How do they get around this problem with the LSP?

**Comment by hsanson** [comment] 2021-01-23 12:21
This has be brought many times already: #3524.  ALE can only fill the quickfix/loclist with errors reported by the underlying linter. If the linter reports errors for other files in the project so will ALE.

Closing as duplicate of #3524

**Closed by hsanson** 2021-01-23 12:21 UTC
Labels: enhancement
