### ISSUE TITLE
Linting the entire project and not just a single file

### ISSUE THREAD

**Issue by refaelsh** [dense-analysis/ale#3524] opened 2021-01-06 07:11 UTC
Hi all,

I would like to propose linting the entire project and not just the current buffer.
I am using Rust and rust-anylzer.

Thanks all.

**Comment by hsanson** [comment] 2021-01-06 09:03
Duplicate of #844 not sure if this was addressed with #653 for language servers.

**Comment by refaelsh** [comment] 2021-01-06 09:22
@hsanson #844 is closed. #653 is also closed and the feature I suggest was not addressed by it.

**Comment by davidatbu** [comment] 2021-01-15 12:58
I think this is something to be addressed in the linter itself (in this case, rust-analyzer).  ALE shows the errors that the linter provides. When I use `mypy` and python, ALE shows errors from all of the files that are in the import chain of the current file because `mypy` yields these errors. ALE does not choke on these errors from other files (ie, I can jump to the error locations in other files the same way that I can for locations in current file).

**Comment by w0rp** [comment] 2021-02-19 21:35
I've been trying to think of something that I might like to have myself, which I can add to ALE as something fun. The idea of linting an entire project came up a very long time ago. I went searching for an existing issue and I found at least this one. The earliest issue I could find is #669.

I have an idea for how to do this, with a wide series of restrictions applied to it. I'll open a new issue for it.

**Closed by w0rp** 2021-02-19 21:35 UTC
Labels: enhancement
