### ISSUE TITLE
esling config issue with monorepos (rush)

### ISSUE THREAD

**Issue by alex-shamshurin** [dense-analysis/ale#2664] opened 2019-07-29 13:35 UTC
When eslint runs from console (executable in local node_modules "apps/project/node_modules/.bin") - it's ok. When it runs through ALE it cannot resolve relative path like `import Something from 'componens/something` though eslint webpack import resolver is configured. I tried to change eslint executable but it didn't help. It resolves only from monorepo root and seems does not looks at eslint's 'import/resolver' section

**Comment by w0rp** [comment] 2019-07-30 20:30
Duplicate of #1546.

I'll close that one too, as you can fix your configuration by using `__dirname`, as mentioned in the documentation.

**Closed by w0rp** 2019-07-30 20:30 UTC
