### ISSUE TITLE
ALE gets caught in endless loop working with Typescript on MacOS

### ISSUE THREAD

**Issue by lwileczek** [dense-analysis/ale#4166] opened 2022-04-23 15:51 UTC
## Information

**VIM version**

```bash
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov  1 2021 21:44:09)
macOS version
Included patches: 1-2029, 3402, 3409, 3428, 3489
```

Operating System: macOS Big Sur Version 11.6.2

## What went wrong

Everytime I open a Typescript file vim freezes. Normally when I open the file it takes a minute to open and the syntax highlighting only works for the first few lines. Then, If I shoot to the bottom with `G` everything freezes. When I check system resources Vim will be pushing at 99% of a core, working _real_ hard. 

I ran `vim -DV9myVim.log myfile.ts` to get logs and when it freezes I get an endless loop of the following:
```bash
Executing CursorMoved Autocommands for "*"
autocommand if exists('*ale#engine#Cleanup') | call ale#cursor#EchoCursorWarningWithDelay() | endif

'redrawtime' exceeded, syntax highlighting disabled
Executing CursorMoved Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing CursorMoved Autocommands for "*"
autocommand if exists('*ale#engine#Cleanup') | call ale#cursor#EchoCursorWarningWithDelay() | endif

Executing CursorMoved Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing CursorMoved Autocommands for "*"
autocommand if exists('*ale#engine#Cleanup') | call ale#cursor#EchoCursorWarningWithDelay() | endif

Executing CursorMoved Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing CursorMoved Autocommands for "*"
autocommand if exists('*ale#engine#Cleanup') | call ale#cursor#EchoCursorWarningWithDelay() | endif

Executing CursorMoved Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing CursorMoved Autocommands for "*"
autocommand if exists('*ale#engine#Cleanup') | call ale#cursor#EchoCursorWarningWithDelay() | endif

Executing CursorMoved Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing CursorMoved Autocommands for "*"
autocommand if exists('*ale#engine#Cleanup') | call ale#cursor#EchoCursorWarningWithDelay() | endif

...
```

I tried turning off ALE for typescript files to no avail:
```vim
" ~/.vim/ftplugin/typescript.vim


" Lint Typescript files and fix them with eslint
let b:ale_enabled = 0 " turn it off plz
let b:ale_linters = {'typescript': ['eslint', 'tsserver']} " ['eslint', 'standard', 'tslint', 'tsserver', 'typecheck', 'xo']
let b:ale_fixers = {'typescript': ['eslint']} " 'eslint' 'prettier' 'remove_trailing_lines' 'trim_whitespace' 'tslint' 'xo'

let g:ale_linters_explicit = 1
let b:ale_linters_explicit = 1

let b:ale_lint_on_text_changed = 'never'
let b:ale_lint_on_insert_leave = 0
let b:ale_lint_on_enter = 0

setlocal textwidth=120
setlocal shiftwidth=2
set regexpengine=2
```

I got the same problem still showing up in my vim logs when vim freezes on the typescript file. 

When I edit a file with `vim --clean myfile.ts` the syntax highlighting breaks instantly (vim problem) but it doesn't freeze. This led me to believe it is indeed a problem loading my ALE issue. Note, I do not have this issue on Linux even though I use ALE on both systems. Only on my macbook pro.

## Reproducing the bug

1. I did this: `vim my-typescript.ts`
  1. `:G` 
3. Then this happened: Freezes, CPU ==> 100%, Log error.

### :ALEInfo
Here is my info when I open the file, I cannot grab the info when it freezes for obvious reasons. Unless there is a way to still get that info and I don't know it yet, very possible. 
```vim
 Current Filetype: typescript
Available Linters: ['cspell', 'deno', 'eslint', 'standard', 'tslint', 'tsserver', 'typecheck', 'xo']
  Enabled Linters: ['eslint', 'tsserver']
  Ignored Linters: []
 Suggested Fixers: 
  'deno' - Fix TypeScript using deno fmt.
  'dprint' - Pluggable and configurable code formatting platform
  'eslint' - Apply eslint --fix to a file.
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'tslint' - Fix typescript files with tslint --fix.
  'xo' - Fix JavaScript/TypeScript files using xo --fix.
 Linter Variables:

let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = v:null
let g:ale_command_wrapper = v:null
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = v:null
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let b:ale_enabled = 0
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let b:ale_fixers = {'typescript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let b:ale_lint_on_enter = 0
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let b:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let b:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {}
let b:ale_linters = {'typescript': ['eslint', 'tsserver']}
let g:ale_linters_explicit = 1
let b:ale_linters_explicit = 1
let g:ale_linters_ignore = {}
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_max_buffer_history_size = v:null
let g:ale_max_signs = v:null
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = v:null
let g:ale_sign_error = v:null
let g:ale_sign_info = v:null
let g:ale_sign_offset = v:null
let g:ale_sign_style_error = v:null
let g:ale_sign_style_warning = v:null
let g:ale_sign_warning = v:null
let g:ale_sign_highlight_linenrs = v:null
let g:ale_statusline_format = v:null
let g:ale_type_map = v:null
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:
```

**Comment by LeonT-A** [comment] 2022-04-26 01:34
I'm experiencing a similar issue with python files, but not a complete crash.

Vim hangs for about 20seconds whenever I open, save, <Esc> out of insert mode, or make any changes to the buffer in normal mode.

I hadn't updated the Ale plugin in years and it started happening after I did it today. Whoops...

**Comment by lwileczek** [comment] 2022-05-03 13:52
I updated Typescript, tsserver, eslint, prettier, and ALE with no avail.

**Comment by hsanson** [comment] 2022-05-04 08:40
Sorry, been trying to see if I can help here but hard since I do not see this problem. Note I do not have Mac available and I do not develop javascript.  

You will need to create a minimal test project with minimal ALE config that can reproduce the issue. Then use git bisect to try find out the commit that caused the problem.

Regarding CursorMoved autocommand it does not seem to be a loop. That autocommand will be invoked every time the cursor is moved so is normal behavior.  These CursorMoved autocommands only activate if echo message or virtual text are enabled so is possible to disable them  with `let g:ale_virtualtext_cursor + 0` and `let g:ale_echo_cursor = 0` and see if this is really the cause of the problem.

**Comment by lwileczek** [comment] 2022-05-13 13:12
With the following `ftplugin/typescript.vim` file
```vim
" ~/.vim/ftplugin/typescript.vim


" Lint Typescript files and fix them with eslint
let b:ale_linters = {'typescript': ['eslint', 'tsserver']} 
let b:ale_fixers = {'typescript': ['eslint', 'prettier']} 
let g:ale_linters_explicit = 1
let b:ale_linters_explicit = 1

let b:ale_enabled = 0 " turn it off plz
let b:ale_lint_on_text_changed = 'never'
let b:ale_lint_on_insert_leave = 0
let b:ale_lint_on_enter = 0
let g:ale_virtualtext_cursor = 0
let g:ale_echo_cursor = 0

setlocal textwidth=120
setlocal shiftwidth=2
set regexpengine=2
```

I still incur the problem. 
```bash
$ ps aux | grep vim
lwileczek            54724  99.5  0.0  4336068   7016 s002  R+    8:59AM   3:08.34 vim create.ts
```

You can see it's using 99.5% of a CPU and I'm unable to move my courser within the file or do anything. It's basically frozen as it's trying to compute something.  I thought it may be related to #1800 but my VIM version is newer than indicated in the issue. 
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov  1 2021 21:44:09)
macOS version
Included patches: 1-2029, 3402, 3409, 3428, 3489
Compiled by root@apple.com
```

I will attempt to use git bisect to find where the bug is but it doesn't seem to have ever really worked for me. I had an older version of ALE and did a git pull to try and get updates to see if I was just out of date. Will report back when I have a small project setup with git bisect.  

If there are any specific logs I can somehow gather to help as well please let me know.

**Comment by lwileczek** [comment] 2022-05-13 15:19
Appears to actually be a VIM syntax highlighting issue not ALE issue. Sorry.
https://vi.stackexchange.com/questions/25086/vim-hangs-when-i-open-a-typescript-file/28721#28721?newreg=b7e9e7a35a2e4ee8806d1900d1c07455

**Comment by hsanson** [comment] 2022-05-15 02:03
Glad you found the issue, hope it gets solved.

**Closed by hsanson** 2022-05-15 02:03 UTC
Labels: bug
