### ISSUE TITLE
Error detected while processing function ale#highlight#UpdateHighlights

### ISSUE THREAD

**Issue by tomarrell** [dense-analysis/ale#2760] opened 2019-09-09 18:40 UTC
## Information

**VIM version**

NVIM v0.3.8
Build type: Release

Operating System: MacOS 10.14.6

## What went wrong

When C-o returning to a buffer with an error in it, the follow error is produced:

![Screenshot 2019-09-09 at 20 29 32](https://user-images.githubusercontent.com/7939459/64556924-b801bc80-d340-11e9-843b-eadd4fc213b5.png)

```
Error detected while processing function ale#highlight#UpdateHighlights[29]..<SNR>172_highlight_range[3]..<SNR>172_matchaddpos[15]..ale#highlight#nvim_buf_add_highlight:
line    1:
Line number outside range
```

This occurs using the latest version of ALE downloaded using Plug, and the latest version of Gopls as the language server running in a Go buffer. 

The linting error in the Go buffer is an unused variable error. The error will only occur when jumping back from a file within the same project.

Interestingly, sometimes when pressing ENTER, further errors occur up to a maximum of three.
```
Error detected while processing function <SNR>162_NeoVimCallback[4]..ale#util#JoinNeovimOutput[2]..<lambda>12[1]..ale#lsp#HandleMessage[30]..ale#lsp_linter#HandleLSPResponse[8]..<SNR>163_HandleLSPDiagnosti
cs[16]..ale#engine#HandleLoclist[40]..ale#engine#SetResults[19]..ale#highlight#SetHighlights[10]..ale#highlight#UpdateHighlights[29]..<SNR>172_highlight_range[3]..<SNR>172_matchaddpos[15]..ale#highlight#nv
im_buf_add_highlight:
line    1:
Line number outside range
Press ENTER or type command to continue
Error detected while processing function <SNR>162_NeoVimCallback[29]..<lambda>38[1]..<SNR>159_ExitCallback[28]..<SNR>121_HandleExit[45]..ale#engine#HandleLoclist[40]..ale#engine#SetResults[19]..ale#highlig
ht#SetHighlights[10]..ale#highlight#UpdateHighlights[29]..<SNR>172_highlight_range[3]..<SNR>172_matchaddpos[15]..ale#highlight#nvim_buf_add_highlight:
line    1:
Line number outside range
Press ENTER or type command to continue
Error detected while processing function <SNR>162_NeoVimCallback[29]..<lambda>39[1]..<SNR>159_ExitCallback[28]..<SNR>121_HandleExit[45]..ale#engine#HandleLoclist[40]..ale#engine#SetResults[19]..ale#highlig
ht#SetHighlights[10]..ale#highlight#UpdateHighlights[29]..<SNR>172_highlight_range[3]..<SNR>172_matchaddpos[15]..ale#highlight#nvim_buf_add_highlight:
line    1:
Line number outside range
Press ENTER or type command to continue
```

## Reproducing the bug
1. Create a new Go project.
2. Add a function in one file, with a call to it in another. 
3. Jump to definition of the function in another file.
4. Jump back
5. Error occurs

### :ALEInfo
```
 Current Filetype: go
Available Linters: ['bingo', 'gobuild', 'gofmt', 'golangci-lint', 'golint', 'gometalinter', 'gopls', 'gosimple', 'gotype', 'govet', 'golangserver', 'staticcheck']
   Linter Aliases:
'gobuild' -> ['go build']
'govet' -> ['go vet']
  Enabled Linters: ['gofmt', 'golint', 'gopls']
 Suggested Fixers: 
  'gofmt' - Fix Go files with go fmt.
  'goimports' - Fix Go files imports with goimports.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_go_go_executable = 'go'
let g:ale_go_golangci_lint_executable = 'golangci-lint'
let g:ale_go_golangci_lint_options = '--enable-all'
let g:ale_go_golangci_lint_package = 0
let g:ale_go_golint_executable = 'golint'
let g:ale_go_golint_options = ''
let g:ale_go_gopls_executable = 'gopls'
let g:ale_go_gopls_options = '--mode stdio'
let g:ale_go_langserver_executable = 'go-langserver'
let g:ale_go_langserver_options = ''
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'go': ['goimports'], 'javascript': ['prettier'], 'css': ['stylelint', 'prettier']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = v:null
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'go': ['gofmt', 'golint', 'gopls'], 'rust': ['rls'], 'javascript': ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'xo'], 'ruby': ['solargraph'], 'css': ['stylelint']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = v:null
let g:ale_list_window_size = v:null
let g:ale_loclist_msg_format = v:null
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = v:null
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) gofmt
(finished - exit code 0) ['/bin/zsh', '-c', '''gofmt'' -e ''/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/2/pageviewHandlers.go''']

<<<NO OUTPUT RETURNED>>>

(executable check - success) golint
(finished - exit code 0) ['/bin/zsh', '-c', '''golint'' ''/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/3/pageviewHandlers.go''']

<<<OUTPUT STARTS>>>
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/3/pageviewHandlers.go:80:6: exported type PathResponse should have comment or be unexported
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/3/pageviewHandlers.go:86:6: exported type PathChanResult should have comment or be unexported
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/3/pageviewHandlers.go:91:1: comment on exported method Endpoint.GetTopPathsHandlerByTime should be of the form "GetTopPathsHandlerByTime ..."
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/3/pageviewHandlers.go:138:6: exported type ReferrerResponse should have comment or be unexported
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/3/pageviewHandlers.go:144:6: exported type ReferrerChanResult should have comment or be unexported
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/3/pageviewHandlers.go:188:6: exported type CountResponse should have comment or be unexported
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/3/pageviewHandlers.go:192:6: exported type DateCount should have comment or be unexported
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/3/pageviewHandlers.go:197:1: comment on exported method Endpoint.GetBucketedCountByTime should be of the form "GetBucketedCountByTime ..."
<<<OUTPUT ENDS>>>

(executable check - success) gopls
(started) ['/bin/zsh', '-c', '''gopls'' --mode stdio']
(finished - exit code 0) ['/bin/zsh', '-c', '''gofmt'' -e ''/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/7/pageviewHandlers.go''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 0) ['/bin/zsh', '-c', '''golint'' ''/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/8/pageviewHandlers.go''']

<<<OUTPUT STARTS>>>
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/8/pageviewHandlers.go:80:6: exported type PathResponse should have comment or be unexported
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/8/pageviewHandlers.go:86:6: exported type PathChanResult should have comment or be unexported
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/8/pageviewHandlers.go:91:1: comment on exported method Endpoint.GetTopPathsHandlerByTime should be of the form "GetTopPathsHandlerByTime ..."
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/8/pageviewHandlers.go:138:6: exported type ReferrerResponse should have comment or be unexported
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/8/pageviewHandlers.go:144:6: exported type ReferrerChanResult should have comment or be unexported
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/8/pageviewHandlers.go:188:6: exported type CountResponse should have comment or be unexported
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/8/pageviewHandlers.go:192:6: exported type DateCount should have comment or be unexported
/var/folders/c3/2l8kp8gj3g3770ypn01rj8th0000gp/T/nvimT05Szy/8/pageviewHandlers.go:197:1: comment on exported method Endpoint.GetBucketedCountByTime should be of the form "GetBucketedCountByTime ..."
<<<OUTPUT ENDS>>>
```

**Comment by tomarrell** [comment] 2019-09-09 18:52
@frangio I notice your changes updating the usage of Neovim's highlight API were added a week ago. Wondering if these may be related. Manually checking out into the v2.5.0 version actually prevents this issue from occurring.

**Comment by Rigellute** [comment] 2019-09-11 08:07
Thanks for finding this. I am doing this temporary workaround for now (it checks out to one commit before the commit you found that introduces the problem).

`cd` to your local `ale` directory (e.g `cd ~/.config/nvim/plugged/ale `)

```bash
git checkout 7d7ddf22d327e6d5369c3331d30c76a35726ce41^
```

**Comment by frangio** [comment] 2019-09-11 15:45
Can you please share a set of go files to test this with?

**Comment by w0rp** [comment] 2019-09-11 15:50
@frangio @andreypopp NeoVim highlighting is broken again for the same reason I reverted it while ago. I have now fixed this by ignoring all errors when adding NeoVim highlights.

**Closed** 2019-09-11 15:49 UTC

**Comment by frangio** [comment] 2019-09-11 16:02
I was not able to reproduce this. I'll appreciate if someone can provide a demo project where the bug is triggered so I can look into the cause.
