### ISSUE TITLE
ansible-lint doesn't parse syntax errors

### ISSUE THREAD

**Issue by Hello-Linux** [dense-analysis/ale#1832] opened 2018-08-21 08:45 UTC
## Information

**VIM version**
version 8.1 centos7.5

Operating System: 

centos7.5

## What went wrong

ansible-lint should not work on ansible playbooks or roles,my vimrc config is 
let g:ale_linters = {                                                                                                       
 \   'python': ['pylint'],                                                                                                   
 \   'ansible': ['ansible-lint'],                                                                                            
 \}
and python check is ok but ansible not work

my step1:
ansible-lint /tmp/vim.yml 
Syntax Error while loading YAML.
  expected <block end>, but found '<block mapping start>'

The error appears to have been in '/tmp/vim.yml': line 8, column 6, I also set let g:ale_completion_enabled = 1
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: nidaye
     lineinfile:
     ^ here
But use vim open it,There is no prompt to open the file!!!!
![error](https://user-images.githubusercontent.com/17851645/44391118-9aa95700-a561-11e8-9871-3c17a5076d0a.png)

Finally,I find the ale  doesn't detect syntax changes in real time Why？？

**Comment by neilhwatson** [comment] 2018-09-12 13:05
I find this report hard to understand. Where is your sample file? What are the expected and actual results?

BTW, I found that you have to tell VIM that your file is an ansible file or it will use yaml filetype instead. You can combine them with :set ft=ansible.yaml.

**Comment by Hello-Linux** [comment] 2018-10-15 10:51
I have set filetype=ansible.yaml  my yaml config is error  but ale no warning why？
![11](https://user-images.githubusercontent.com/17851645/46946752-59d64600-d0ab-11e8-96ab-9d4efd5fb4c9.png)

**Comment by w0rp** [comment] 2018-10-15 18:05
You should include the output of `:ALEInfo`, like the issue template says. Then people can have a look at what output your command returned, and what was run.

**Comment by Hello-Linux** [comment] 2018-10-17 08:03
this is my aleinfo:
![111](https://user-images.githubusercontent.com/17851645/47071448-2bc94100-d226-11e8-9cee-7023835d28d6.png)
![222](https://user-images.githubusercontent.com/17851645/47071458-308df500-d226-11e8-87b8-d04cf033690d.png)

**Comment by Hello-Linux** [comment] 2018-10-17 08:05
I don't think ale's support for ansible is very good,and My ale can't detect syntax changes in python and anble in real time

**Comment by w0rp** [comment] 2018-10-17 08:42
Include the output of `:ALEInfo` so others can see if there's any output from the linter which ALE isn't parsing.

**Comment by Hello-Linux** [comment] 2018-10-17 09:06
yes,you also can my project  include my config for vimrc https://github.com/Hello-Linux/Ansible-VIM-IDE/commit/26fb5ede2346c97ac82839af8b08eaf984515ef3

**Comment by Hello-Linux** [comment] 2018-10-17 09:15
ansible-lint check some errors but ale show nothing why?
![3333](https://user-images.githubusercontent.com/17851645/47075963-43a5c280-d230-11e8-9a87-fe09644a0260.png)
![4444](https://user-images.githubusercontent.com/17851645/47075969-49030d00-d230-11e8-9305-949221ea3f48.png)

**Comment by Hello-Linux** [comment] 2018-10-17 09:16
so I think the ale is not working for ansible

**Comment by Hello-Linux** [comment] 2018-10-17 09:33
Hopefully this problem can be fixed later,My project is currently quoting him, and the other thing you don't pay attention to is that this ale isn't being detected in real time

**Comment by Hello-Linux** [comment] 2018-10-30 07:51
Haven't you solved it yet?

**Comment by w0rp** [comment] 2018-10-31 10:36
Haven't you? I don't tend to work on individual linters too much. I tend to leave that to contributors. I mostly work on the core of ALE itself.

**Comment by Hello-Linux** [comment] 2018-12-10 07:39
ok

**Comment by tterranigma** [comment] 2019-03-18 10:27
I think this is a duplicate of #1814 .

**Comment by timblaktu** [comment] 2019-08-22 23:59
Agreed, @nkakouros these should be collapsed into one so the conversation can focus:
https://github.com/dense-analysis/ale/issues/2171 
https://github.com/dense-analysis/ale/issues/1814 
https://github.com/dense-analysis/ale/issues/1832

Since you're suggesting to keep 1814, I'll comment there.

**Comment by w0rp** [comment] 2019-09-20 19:10
I'll close this and move the discussion to #1814.

**Closed by w0rp** 2019-09-20 19:10 UTC
Labels: bug
