### ISSUE TITLE
Floating preview closes visual modes

### ISSUE THREAD

**Issue by axeldetlofsson** [dense-analysis/ale#3584] opened 2021-02-09 15:42 UTC
## Information

**VIM version**
NVIM v0.5.0-dev+1025-g0fad952a2
Build type: RelWithDebInfo

Operating System: 
Linux Atch 5.10.14 Kernel

## What went wrong
With ale_floating_preview enabled visual I have trouble with visual modes when cursor is at a error/warning. Entering visual mode wont close open floating preview, causing my next cursor move to close open preview but also exit visual mode. I dont know if this a bug or request for a setting like 'let g:ale_close_preview_when_entering_visual = 1' 

## Reproducing the bug

1. Configure ale with theese settings:
let g:ale_floating_preview = 1
let g:ale_hover_to_floating_preview = 1
let g:ale_detail_to_floating_preview = 1
let g:ale_use_global_executables = 1
let g:ale_sign_error = 'x'
let g:ale_sign_warning = '?'
let g:float_preview#docked = 0
let g:ale_cursor_detail = 1
let g:ale_hover_cursor = 1
let g:ale_close_preview_on_insert = 1

2. Go to a line with a error / warning causing floating preview to show.
3. Enter visual mode.
4. Move down a line with j.
5. BUG: you are no longer in visual mode.

### :ALEInfo

 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'fecs', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint', 'tsserver']
  Ignored Linters: []
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'fecs' - Apply fecs format to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript/TypeScript files using xo --fix.
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 1
let g:ale_javascript_tsserver_config_path = ''
let g:ale_javascript_tsserver_executable = 'tsserver'
let g:ale_javascript_tsserver_use_global = 1
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 0
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'jsx': ['prettier'], 'javascript': ['prettier']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 2000
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linter_aliases = {}
let g:ale_linters = {'jsx': ['eslint', 'tsserver'], 'typescript': ['eslint', 'tsserver'], 'javascript': ['eslint', 'tsserver']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {'jsx': ['jshint'], 'javascript': ['jshint'], 'typescript': ['jshint']}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = 'x'
let g:ale_sign_info = '?'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = 'x'
let g:ale_sign_style_warning = '?'
let g:ale_sign_warning = '?'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = 1
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) eslint
(finished - exit code 1) ['/bin/bash', '-c', 'cd ''/home/axel/dev/mspx/backend'' && ''eslint'' -f json --stdin --stdin-filename ''/home/axel/dev/mspx/backend/util/housingassociation-duplication/new.js'' < ''/tmp/nvimHMjbou/4/new.js''']

<<<OUTPUT STARTS>>>
[{"filePath":"/home/axel/dev/mspx/backend/util/housingassociation-duplication/new.js","messages":[{"ruleId":"no-unused-vars","severity":1,"message":"'objArr' is assigned a value but never used.","line":4,"column":7,"nodeType":"Identifier","messageId":"unusedVar","endLine":4,"endColumn":13},{"ruleId":"no-unused-vars","severity":1,"message":"'select' is assigned a value but never used.","line":6,"column":7,"nodeType":"Identifier","messageId":"unusedVar","endLine":6,"endColumn":13},{"ruleId":"no-unused-vars","severity":1,"message":"'id' is defined but never used.","line":11,"column":30,"nodeType":"Identifier","messageId":"unusedVar","endLine":11,"endColumn":32},{"ruleId":"no-tabs","severity":2,"message":"Unexpected tab character.","line":26,"column":1,"nodeType":"Program","messageId":"unexpectedTab","endLine":26,"endColumn":2},{"ruleId":"no-unused-vars","severity":1,"message":"'ACTIONS' is assigned a value but never used.","line":30,"column":7,"nodeType":"Identifier","messageId":"unusedVar","endLine":30,"endColumn":14},{"ruleId":"no-unused-vars","severity":1,"message":"'_throw' is assigned a value but never used.","line":37,"column":32,"nodeType":"Identifier","messageId":"unusedVar","endLine":37,"endColumn":38},{"ruleId":"function-paren-newline","severity":2,"message":"Unexpected newline after '('.","line":37,"column":56,"nodeType":"Punctuator","messageId":"unexpectedAfter","endLine":37,"endColumn":57,"fix":{"range":[905,914],"text":""}},{"ruleId":"function-paren-newline","severity":2,"message":"Unexpected newline before ')'.","line":39,"column":5,"nodeType":"Punctuator","messageId":"unexpectedBefore","endLine":39,"endColumn":6,"fix":{"range":[949,954],"text":""}},{"ruleId":"no-console","severity":1,"message":"Unexpected console statement.","line":41,"column":5,"nodeType":"MemberExpression","messageId":"unexpected","endLine":41,"endColumn":16},{"ruleId":"arrow-parens","severity":2,"message":"Expected parentheses around arrow function argument having a body with curly braces.","line":43,"column":28,"nodeType":"ArrowFunctionExpression","messageId":"expectedParensBlock","endLine":43,"endColumn":33,"fix":{"range":[1047,1052],"text":"(entry)"}},{"ruleId":"no-console","severity":1,"message":"Unexpected console statement.","line":44,"column":9,"nodeType":"MemberExpression","messageId":"unexpected","endLine":44,"endColumn":20}],"errorCount":4,"warningCount":7,"fixableErrorCount":3,"fixableWarningCount":0,"source":"const {\n    internalConnectDB,\n} = require('../export-organization-unit/db/dbConnect');\nconst objArr = require('./object-array');\n\nconst select = (table, key, id) =>\n    `SELECT * FROM ${table} WHERE ${key} = ${id}`;\n\nconst update = (table, id) => `UPDATE ${table} SET ? WHERE id = ${id}`;\n\nconst insert = (table, keys, id) => `INSERT INTO ${table}(${keys}) VALUES ?`;\n\nconst config = {\n    schema: 'mspx_2',\n};\nconst constraints = table => `\nSELECT\n    TABLE_NAME,\n    COLUMN_NAME,\n    CONSTRAINT_NAME,\n    REFERENCED_TABLE_NAME,\n    REFERENCED_COLUMN_NAME\nFROM\n    INFORMATION_SCHEMA.KEY_COLUMN_USAGE\nWHERE\n\tREFERENCED_TABLE_SCHEMA = '${config.schema}'\nAND REFERENCED_TABLE_NAME = '${table}';\n`;\n\nconst ACTIONS = {\n    CLONE: insert,\n    UPDATE: update,\n};\n\nconst main = async () => {\n    const db = await internalConnectDB(config.schema, false);\n    const [housingConstraints, _throw] = await db.query(\n        constraints('housingAssociations'),\n    );\n\n    console.log('housingConstraints: ', housingConstraints);\n\n    housingConstraints.map(entry => {\n        console.log('entry: ', entry);\n        return null;\n    });\n\n    db.end();\n};\n\nmain();\n","usedDeprecatedRules":[{"ruleId":"lines-around-directive","replacedBy":["padding-line-between-statements"]},{"ruleId":"no-spaced-func","replacedBy":["func-call-spacing"]},{"ruleId":"global-require","replacedBy":[]},{"ruleId":"no-buffer-constructor","replacedBy":[]},{"ruleId":"no-new-require","replacedBy":[]},{"ruleId":"no-path-concat","replacedBy":[]}]}]
<<<OUTPUT ENDS>>>

(executable check - success) tsserver
(started) ['/bin/bash', '-c', '''tsserver''']

**Comment by puresick** [comment] 2021-03-24 16:21
Maybe @kevinclark can help with this - he initially implemented the floating window support :)

**Comment by kevinclark** [comment] 2021-03-25 04:59
Ah yes. I remember this. It *is* obnoxious isn't it. If I understand it right, the problem is fundamentally that 'call' exits visual mode. We've got to do a lot of that to create floating windows and to close them. I think the autocmd that closes when the cursor moves is the culprit. I think I have a fix. Just a sec and I'll push a branch up you can try out.

**Comment by kevinclark** [comment] 2021-03-25 05:03
Give [this branch] a shot and I'll see about adding tests so it could actually get merged.

**Comment by kevinclark** [comment] 2021-03-25 05:40
Hm. It looks like visual mode isn't preserved across vader test blocks. I'm not sure how to get around that and write a test for it. If I can get some people to vouch for the change, I'll see if someone will accept it anyway 🤷‍♂️

**Comment by kevinclark** [comment] 2021-04-07 00:02
@axeldetlofsson @puresick If one of you can try out my fix, I'd try to move this further along...

**Comment by puresick** [comment] 2021-04-10 20:22
@kevinclark Sorry for the late reply!
I just tested your branch mentioned above with neovim v0.4.4 and it works like a charm - nice work :+1:

**Comment by kevinclark** [comment] 2021-04-12 06:07
Thanks! PR is up!

**Comment by puresick** [comment] 2021-04-12 07:31
Thank you for your quick work! 🥇

**Comment by hsanson** [comment] 2021-04-12 07:57
Hopefully solved with #3689

**Closed by hsanson** 2021-04-12 07:57 UTC
Labels: bug

**Comment by axeldetlofsson** [comment] 2021-04-13 12:05
Sorry for not helping with testing, had alot on my table. Thanks for the fast fix, works great!
