### ISSUE TITLE
Implement ALEFix on Visual Selection

### ISSUE THREAD

**Issue by Konstantin-Glukhov** [dense-analysis/ale#4549] opened 2023-07-07 05:00 UTC
Please don't tell it does not make sense to do it.
It can be done in many ways. One of them is described in this [StackExchange answer](https://vi.stackexchange.com/questions/30836/ale-fix-for-a-visual-selection)
Another idea is to save selection in a temporary file (you do it anyway by saving the whole buffer in a temporary file) and then calling a fixer, and replacing selection with the fixed contents.

**Comment by pbnj** [comment] 2023-07-14 02:38
I am not sure that this is a good idea since this might not be supported by all fixers.

In this case, what should the outcome be? Return an error? Implicitly fix the whole buffer?

Also, the stackexchange answer is more complicated than it should be.
I recommend using Vim's built-in `:h formatprg` for this.
For example, if you want to format over a range in a markdown file using `prettier`, then you can do this:

```viml
:let &l:formatprg='prettier --parser markdown'
```

Or with `:set` syntax:

```viml
:setlocal formatprg=prettier\ --parser\ markdown
```

Or in your vimrc:

```viml
augroup RangeFixer
  autocmd!
  autocmd FileType markdown let &l:formatprg='prettier --parser markdown'
augroup END
```

This will set the `formatprg` option to `prettier --parser markdown` for the local buffer only, then you can highlight the range you want and press `gq` (see [`:h gq`](https://vimdoc.sourceforge.net/htmldoc/change.html#gq)).

**Comment by Konstantin-Glukhov** [comment] 2023-07-20 08:33
Thank you for the tips on formatprg.

Though I still think it can be implemented for any formatter with the following algorithm:

1. Save selection into a temp buffer
2. Format a temp buffer
3. Delete selection
4. Insert formatted temp buffer at the position of deletion.

**Comment by w0rp** [comment] 2023-08-20 07:39
This is a duplicate of https://github.com/dense-analysis/ale/issues/850. Not all tools can support fixing only a range of lines. I believe most don't. My recommendation to write smaller files in projects is still not a joke.

**Closed by w0rp** 2023-08-20 07:39 UTC
Labels: enhancement
