### ISSUE TITLE
Change default ALEErrorSign highlighting colors

### ISSUE THREAD

**Issue by cbix** [dense-analysis/ale#3100] opened 2020-04-10 18:32 UTC
I'm using gnome-terminal on Arch Linux and the contrast of vim-ale's error highlighting colors is too low IMO, making a lot of code unreadable with any of the built-in color schemes:
![example1](https://user-images.githubusercontent.com/1295945/79013753-ae0b9a80-7b69-11ea-98af-60f3ca035aac.png)
![example2](https://user-images.githubusercontent.com/1295945/79013754-aea43100-7b69-11ea-9766-7fd942fc4ecd.png)

I know I can change or disable these colors myself through vimrc, but for the default values you might want to choose something with more contrast.

Anyway, thanks for this great plugin!

**Comment by RyanSquared** [comment] 2020-04-10 18:52
I think it would be useful to have a setting for "high contrast vs light colors" and "high contrast vs dark colors", probably based off of &background == "dark". I don't know enough about Vim colorschemes to look into it more, though.

**Comment by RyanSquared** [comment] 2020-04-10 18:56
Actually, my terminal has a much darker "dark red" than yours does. I hate to put the blame on the terminal, but if that's the "dark red" background color (as opposed to bright red - which it's not as bright as mine, so I'm conflicted on which it is), then ALE would be working as intended, but your terminal itself needs a higher-contrasts colorscheme.

**Comment by RyanSquared** [comment] 2020-04-10 18:59
Did a bit of testing and it looks like the default colorscheme sets SpellBad (which I've found that ALEError's highlight links to) is colored "bright red". I think this is an issue with Vim and should ideally be fixed by Vim's SpellBad using a dark red for higher contrast.

**Comment by CBiX** [comment] 2020-04-10 22:23
That makes sense then, I also found more people complaining about the SpellBad highlighting.
Like I wrote, I have this issue with all the color scheme presets, some are even worse with purple on red, which is basically the same color when I have Gnome's night mode turned on :D 
![stupid example](https://user-images.githubusercontent.com/1295945/79026458-30578700-7b89-11ea-8a26-3ca617be5c43.png)

But now I'm curious why it's using dark red for you.

**Comment by RyanSquared** [comment] 2020-04-10 22:25
I wasn't using the default colorscheme at the time, was using one that sets SpellBad to dark red. I thought ALE was setting it's own one instead of linking to SpellBad, in which case it would have been a definite error on ALE's side.

**Comment by hsanson** [comment] 2021-08-03 15:03
Not ALE issue. Closing.

**Closed by hsanson** 2021-08-03 15:03 UTC
Labels: enhancement

**Comment by yc-zzh** [comment] 2021-11-02 12:48
How do I change the green color?
![image](https://user-images.githubusercontent.com/43780800/139849430-eb5559ed-9916-4bce-8908-7e0512a406ae.png)
