### ISSUE TITLE
TSLint errors complete ignored (Win10/NeoVim)

### ISSUE THREAD

**Issue by foxbunny** [dense-analysis/ale#1355] opened 2018-02-17 18:35 UTC
## Information

**VIM version**

![image](https://user-images.githubusercontent.com/65413/36344304-abe6d72a-1418-11e8-8acc-522f90b4a645.png)

Operating System: Windows 10, 64-bit.

### :ALEInfo

```

 Current Filetype: typescript
Available Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
  Enabled Linters: ['tslint', 'tsserver']
 Linter Variables:

let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'typescript': ['tslint'], 'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'typescript': ['tslint', 'tsserver'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - failure) xmllint
(executable check - success) C:\Code\cgfe\node_modules\.bin\tslint
(finished - exit code 0) 'cmd /s/c "cd C:\Code\cgfe\src\company && C:\Code\cgfe\node_modules\.bin\tslint --format json -c C:\Code\cgfe\tslint.json C:\Users\HAJIME~1\AppData\Local\Temp\nvim5D8rwd\2\model.ts"'

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>

(started) 'cmd /s/c "C:\Code\cgfe\node_modules\.bin\tsserver"'
(started) 'cmd /s/c "cd C:\Code\cgfe\src\company && C:\Code\cgfe\node_modules\.bin\tslint --format json -c C:\Code\cgfe\tslint.json C:\Users\HAJIME~1\AppData\Local\Temp\nvim5D8rwd\3\model.ts"'
(finished - exit code 2) 'cmd /s/c "cd C:\Code\cgfe\src\company && C:\Code\cgfe\node_modules\.bin\tslint --format json -c C:\Code\cgfe\tslint.json C:\Users\HAJIME~1\AppData\Local\Temp\nvim5D8rwd\4\model.ts"'

<<<OUTPUT STARTS>>>
[{"endPosition":{"character":21,"line":10,"position":173},"failure":"Named imports must be alphabetized.","fix":[{"innerStart":60,"innerLength":467,"innerText":"import CONFIG from \"config\";\nimport {\n  Address,\n  CidProperty,\n  CidPropertyWithCode,\n  CidPropertyWithShorthand,\n  Currency,\n  LocalName,\n  PhoneNumber,\n  RelatedEntity,\n  TextProperty,\n  TextPropertyWithDescription,\n  toAddressString,\n  toDatestamp,\n  toEnglishName,\n  toEntityName,\n  toLocalizedString,\n  toLocalName,\n  ValueTrend,\n} from \"data/response\";\nimport P from \"platform\";\nimport {collectProperties} from \"util/obj\";\nimport xhr, {HttpMethod} from \"xhr\";\n"}],"name":"C:/Users/HAJIME~1/AppData/Local/Temp/nvim5D8rwd/4/model.ts","ruleName":"ordered-imports","ruleSeverity":"ERROR","startPosition":{"character":2,"line":9,"position":126}}]
<<<OUTPUT ENDS>>>

(started) 'cmd /s/c "cd C:\Code\cgfe\src\company && C:\Code\cgfe\node_modules\.bin\tslint --format json -c C:\Code\cgfe\tslint.json C:\Users\HAJIME~1\AppData\Local\Temp\nvim5D8rwd\5\model.ts"'
(finished - exit code 0) 'cmd /s/c "cd C:\Code\cgfe\src\company && C:\Code\cgfe\node_modules\.bin\tslint --format json -c C:\Code\cgfe\tslint.json C:\Users\HAJIME~1\AppData\Local\Temp\nvim5D8rwd\6\model.ts"'

<<<OUTPUT STARTS>>>
[]
<<<OUTPUT ENDS>>>
```

## What went wrong

If I modify the code in a way that I know is going to trip TSLint (e.g., wrong order of imports) ALE does not show anything.

Fixing the error in the file on save works fine.

## Reproducing the bug

[TSLint config](https://gist.github.com/foxbunny/65bbecc316d4aa207f9fedc68140c433)

**Comment by noahbrenner** [comment] 2018-12-26 09:38
I believe I'm running into the same issue on Windows 7 (32-bit) with VIM 8, which suggests that the issue isn't specific to NeoVim. Let me know if what I'm getting isn't the same issue and I'll be happy to post a separate one.

* Type checking through `tsserver` works as expected: Errors are reported within the editor window.
* However, even though `tslint` is reporting errors to `ALE` (which can be seen via `ALEInfo`), these errors are not displayed in the editor. I couldn't get the errors to display with any trigger, whether opening the file, editing the buffer, saving the file, or manually running `ALELint`.

I do plan to try the `tsserver` plugin workaround as well, but it would also be helpful to have the option of using `tslint` directly, since it *is* reporting errors correctly in this case.

<details>
<summary>Click for full VIM version</summary>

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 17 2017 09:12:04)
Included patches: 1-1305
Compiled by <alexpux@gmail.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-autoservername  +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     +gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
+clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        +perl/dyn        +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim80"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2 -I/usr/include/ncursesw  -marc
h=i686 -mtune=generic -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -pipe -fstack-protector -pipe -Wl,--as-needed -o vim.exe        -lm    -lncursesw
 -liconv -lacl -lintl   -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-ba
se -fstack-protector-strong  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -ldl -lcrypt
```

</details>

<details>
<summary>Click for ALEInfo output</summary>

```
 Current Filetype: typescript
Available Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
  Enabled Linters: ['eslint', 'tslint', 'tsserver', 'typecheck']
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'prettier' - Apply prettier to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'tslint' - Fix typescript files with tslint --fix.
 Linter Variables:

let g:ale_typescript_tslint_config_path = ''
let g:ale_typescript_tslint_executable = 'tslint'
let g:ale_typescript_tslint_ignore_empty_files = 0
let g:ale_typescript_tslint_rules_dir = ''
let g:ale_typescript_tslint_use_global = 0
let g:ale_typescript_tsserver_config_path = ''
let g:ale_typescript_tsserver_executable = 'tsserver'
let g:ale_typescript_tsserver_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_linter_aliases = {}
let g:ale_linters = {'python': ['pycodestyle']}
let g:ale_linters_explicit = 0
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 1
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(started) 'cmd /s/c "cd /d D:\Harper\js\bookmarklets\fb-event-attendees\src && D:\Harper\js\bookmarklets\fb-event-attendees\node_modules\.bin\tslint --format json -c D:\Harper\js\bookmarklets\fb-event-attendees\tslint.json C:\Users\Harper\AppData\Local\Temp\VIND7BD.tmp\index.ts"'
(executable check - failure) typecheck
(executable check - failure) eslint
(finished - exit code 2) 'cmd /s/c "cd /d D:\Harper\js\bookmarklets\fb-event-attendees\src && D:\Harper\js\bookmarklets\fb-event-attendees\node_modules\.bin\tslint --format json -c D:\Harper\js\bookmarklets\fb-event-attendees\tslint.json C:\Users\Harper\AppData\Local\Temp\VIPDC02.tmp\index.ts"'

<<<OUTPUT STARTS>>>
[{"endPosition":{"character":121,"line":16,"position":734},"failure":"Exceeds maximum line length of 80","name":"C:/Users/Harper/AppData/Local/Temp/VIPDC02.tmp/index.ts","ruleName":"max-line-length","ruleSeverity":"ERROR","startPosition":{"character":0,"line":16,"position":613}},{"endPosition":{"character":85,"line":28,"position":1133},"failure":"Exceeds maximum line length of 80","name":"C:/Users/Harper/AppData/Local/Temp/VIPDC02.tmp/index.ts","ruleName":"max-line-length","ruleSeverity":"ERROR","startPosition":{"character":0,"line":28,"position":1048}},{"endPosition":{"character":84,"line":56,"position":1787},"failure":"Exceeds maximum line length of 80","name":"C:/Users/Harper/AppData/Local/Temp/VIPDC02.tmp/index.ts","ruleName":"max-line-length","ruleSeverity":"ERROR","startPosition":{"character":0,"line":56,"position":1703}},{"endPosition":{"character":12,"line":2,"position":131},"failure":"unused expression, expected an assignment or function call","name":"C:/Users/Harper/AppData/Local/Temp/VIPDC02.tmp/index.ts","ruleName":"no-unused-expression","ruleSeverity":"ERROR","startPosition":{"character":0,"line":2,"position":119}},{"endPosition":{"character":12,"line":2,"position":131},"failure":"Missing semicolon","fix":{"innerStart":131,"innerLength":0,"innerText":";"},"name":"C:/Users/Harper/AppData/Local/Temp/VIPDC02.tmp/index.ts","ruleName":"semicolon","ruleSeverity":"ERROR","startPosition":{"character":12,"line":2,"position":131}}]
<<<OUTPUT ENDS>>>

(executable check - failure) typecheck
(executable check - failure) eslint
(started) 'cmd /s/c "cd /d D:\Harper\js\bookmarklets\fb-event-attendees\src && D:\Harper\js\bookmarklets\fb-event-attendees\node_modules\.bin\tslint --format json -c D:\Harper\js\bookmarklets\fb-event-attendees\tslint.json C:\Users\Harper\AppData\Local\Temp\VIQFABA.tmp\index.ts"'
(executable check - failure) typecheck
(executable check - failure) eslint
(finished - exit code 2) 'cmd /s/c "cd /d D:\Harper\js\bookmarklets\fb-event-attendees\src && D:\Harper\js\bookmarklets\fb-event-attendees\node_modules\.bin\tslint --format json -c D:\Harper\js\bookmarklets\fb-event-attendees\tslint.json C:\Users\Harper\AppData\Local\Temp\VIR20B.tmp\index.ts"'

<<<OUTPUT STARTS>>>
[{"endPosition":{"character":121,"line":15,"position":721},"failure":"Exceeds maximum line length of 80","name":"C:/Users/Harper/AppData/Local/Temp/VIR20B.tmp/index.ts","ruleName":"max-line-length","ruleSeverity":"ERROR","startPosition":{"character":0,"line":15,"position":600}},{"endPosition":{"character":85,"line":27,"position":1120},"failure":"Exceeds maximum line length of 80","name":"C:/Users/Harper/AppData/Local/Temp/VIR20B.tmp/index.ts","ruleName":"max-line-length","ruleSeverity":"ERROR","startPosition":{"character":0,"line":27,"position":1035}},{"endPosition":{"character":84,"line":55,"position":1774},"failure":"Exceeds maximum line length of 80","name":"C:/Users/Harper/AppData/Local/Temp/VIR20B.tmp/index.ts","ruleName":"max-line-length","ruleSeverity":"ERROR","startPosition":{"character":0,"line":55,"position":1690}}]
<<<OUTPUT ENDS>>>

(executable check - failure) typecheck
(executable check - failure) eslint
(finished - exit code 2) 'cmd /s/c "cd /d D:\Harper\js\bookmarklets\fb-event-attendees\src && D:\Harper\js\bookmarklets\fb-event-attendees\node_modules\.bin\tslint --format json -c D:\Harper\js\bookmarklets\fb-event-attendees\tslint.json C:\Users\Harper\AppData\Local\Temp\VIS15AB.tmp\index.ts"'

<<<OUTPUT STARTS>>>
[{"endPosition":{"character":121,"line":15,"position":721},"failure":"Exceeds maximum line length of 80","name":"C:/Users/Harper/AppData/Local/Temp/VIS15AB.tmp/index.ts","ruleName":"max-line-length","ruleSeverity":"ERROR","startPosition":{"character":0,"line":15,"position":600}},{"endPosition":{"character":85,"line":27,"position":1120},"failure":"Exceeds maximum line length of 80","name":"C:/Users/Harper/AppData/Local/Temp/VIS15AB.tmp/index.ts","ruleName":"max-line-length","ruleSeverity":"ERROR","startPosition":{"character":0,"line":27,"position":1035}},{"endPosition":{"character":84,"line":55,"position":1774},"failure":"Exceeds maximum line length of 80","name":"C:/Users/Harper/AppData/Local/Temp/VIS15AB.tmp/index.ts","ruleName":"max-line-length","ruleSeverity":"ERROR","startPosition":{"character":0,"line":55,"position":1690}}]
<<<OUTPUT ENDS>>>

(executable check - failure) typecheck
(executable check - failure) eslint
(started) 'cmd /s/c "cd /d D:\Harper\js\bookmarklets\fb-event-attendees\src && D:\Harper\js\bookmarklets\fb-event-attendees\node_modules\.bin\tslint --format json -c D:\Harper\js\bookmarklets\fb-event-attendees\tslint.json C:\Users\Harper\AppData\Local\Temp\VIT82C1.tmp\index.ts"'
(executable check - failure) typecheck
(executable check - failure) eslint
(finished - exit code 2) 'cmd /s/c "cd /d D:\Harper\js\bookmarklets\fb-event-attendees\src && D:\Harper\js\bookmarklets\fb-event-attendees\node_modules\.bin\tslint --format json -c D:\Harper\js\bookmarklets\fb-event-attendees\tslint.json C:\Users\Harper\AppData\Local\Temp\VIU8457.tmp\index.ts"'

<<<OUTPUT STARTS>>>
[{"endPosition":{"character":121,"line":15,"position":721},"failure":"Exceeds maximum line length of 80","name":"C:/Users/Harper/AppData/Local/Temp/VIU8457.tmp/index.ts","ruleName":"max-line-length","ruleSeverity":"ERROR","startPosition":{"character":0,"line":15,"position":600}},{"endPosition":{"character":85,"line":27,"position":1120},"failure":"Exceeds maximum line length of 80","name":"C:/Users/Harper/AppData/Local/Temp/VIU8457.tmp/index.ts","ruleName":"max-line-length","ruleSeverity":"ERROR","startPosition":{"character":0,"line":27,"position":1035}},{"endPosition":{"character":84,"line":55,"position":1774},"failure":"Exceeds maximum line length of 80","name":"C:/Users/Harper/AppData/Local/Temp/VIU8457.tmp/index.ts","ruleName":"max-line-length","ruleSeverity":"ERROR","startPosition":{"character":0,"line":55,"position":1690}}]
<<<OUTPUT ENDS>>>

(executable check - failure) typecheck
```

</details>

**Comment by w0rp** [comment] 2018-12-27 17:54
Okay. I do generally recommend using the `tsserver` plugin instead, and separately running `tslint` on your whole project now and again say in CI, or via some script. I don't expect `tslint` to work that well.

**Comment by noahbrenner** [comment] 2018-12-27 20:40
Understood, I just wanted to provide the little data I found, since `ALE` isn't displaying the errors that `tslint` *is* reporting.

What would you think of updating the README/man page about this so that people don't expect `tslint` to work the same way as other linters (and then bug you about it when they run into that)? One option would be to remove `tslint` from the list, but I think a better option would be to mention that it doesn't usually work directly with `ALE`, but that it can work using a plugin (and provide the link).

Speaking of that plugin, [angelozerr/tslint-language-service](https://github.com/angelozerr/tslint-language-service) is now deprecated, but [Microsoft/typescript-tslint-plugin](https://github.com/Microsoft/typescript-tslint-plugin) is a fork of it, recommended by the original developer and now maintained by the same folks who develop TypeScript itself. It works the same way as the original plugin, and I've successfully used it with `ALE`. I'd recommend pointing people to this new project if you provide that type of suggestion in the documentation.

Let me know if there's any way I can help.

**Comment by w0rp** [comment] 2019-01-03 20:30
If you can see them in ALEInfo, maybe the function which parses the results isn't parsing them correctly.

**Comment by noahbrenner** [comment] 2019-01-04 00:34
@w0rp Yeah, that's what I suspect is happening in this case. Is there a good way of debugging the parsing function that you'd recommend?

**Comment by noahbrenner** [comment] 2019-01-06 01:55
Excellent, thanks for the pointers! I'll work on that when I get some time.

**Comment by w0rp** [comment] 2019-08-18 14:25
I'll close this and other TSLint issues I find, as TSLint is deprecated. I recommend switching to ESLint. https://github.com/palantir/tslint/issues/4534

**Closed by w0rp** 2019-08-18 14:25 UTC
Labels: bug
