### ISSUE TITLE
Fix/improve ansible-lint

### ISSUE THREAD

**Issue by ihatemicrosoft-was-already-taken** [dense-analysis/ale#2171] opened 2018-12-30 16:21 UTC
The `ansible-lint` linter is a bit special in a way that it might expect particular entrypoints (start directories) rather than a single file. Apart from that there's the issue that Ansible uses YAML files, so there needs to be some kind of distinction logic to determine whether a `.yml` or `.yaml` is an Ansible file or not. If it is, the filetype should be set to `ansible.yaml` (or `yaml.ansible`? Don't know if that makes a difference) and to `yaml` otherwise.

For the distinction logic, I would like to propose a check of directories. If the file is in a directory containing `/roles/` or if a directory on the same level (depth) in the file system is called `/roles/` treat the YAML file as Ansible.

See https://github.com/chase/vim-ansible-yaml/pull/48/commits/c670bc0912977be5f9c2268dbfe9ce871f8d1eed and https://github.com/pearofducks/ansible-vim/blob/master/ftdetect/ansible.vim for examples (more paths, like in pearofducks/ansible-vim) could be added.

Now to the invocation logic. According to https://github.com/ansible/ansible-lint one can invoke `ansible-lint` from within a single role or directly on a playbook file. As the output (especially on a role) could contain more than the file actually being edited the output has to be filtered for that file.

So, if a file within a role is edited, `ansible-lint` has to be executed on that role and the output filtered for the file. If the file is not within a role, execution on the file itself could be attempted. I have quickly hacked a bash script which basically does just that:

```
#!/bin/bash

ENTRYPATH=$( realpath "$1" )

if [[ "${ENTRYPATH}" == *"roles"* ]]; then
    # File is within a role so let's execute ansible-lint for that particular role
    ansible-lint -p \
      "$( echo "${ENTRYPATH}" | perl -ne 's!^(.*)(/roles/[^/]+/).*!\1\2! and print' )" | \
      grep "${ENTRYPATH}" ; \
      exit "${PIPESTATUS[0]}"
else
    # File could be a playbook, so let's use that for analysis
    ansible-lint -p "${ENTRYPATH}" | grep "${ENTRYPATH}" ; \
    exit "${PIPESTATUS[0]}"
fi
```
I debugged a little and found that a temporary file is copied to `/tmp` for the actual analysis. On the one hand that makes sense, but on the other hand `ansible-lint` unfortunately only works in the context it's being executed in (i.e. the whole directory tree the Ansible files are saved in). I thought I could use my script as a workaround, but that obviosly wouldn't work. ;)

I don't have any idea of the inner workings of ALE or vim scripting, but maybe this will help someone fixing the Ansible linter some day.

**Comment by w0rp** [comment] 2018-12-31 10:56
Whatever we do, make sure it will also work on BSD, Mac OSX, and Windows.

**Comment by ihatemicrosoft-was-already-taken** [comment] 2019-01-02 14:56
Absolutely, I just wanted to point out the inner workings of ansible-lint itself.

**Comment by w0rp** [comment] 2019-01-05 17:00
Sure.

**Comment by tterranigma** [comment] 2019-03-18 10:26
I think this is a duplicate of #1814 .

**Comment by timblaktu** [comment] 2019-08-22 23:58
Agreed, @nkakouros these should be collapsed into one so the conversation can focus:
https://github.com/dense-analysis/ale/issues/2171 
https://github.com/dense-analysis/ale/issues/1814 
https://github.com/dense-analysis/ale/issues/1832

Since you're suggesting to keep 1814, I'll comment there.

**Comment by w0rp** [comment] 2019-09-20 19:11
Discussion moved to  #1814.

**Closed by w0rp** 2019-09-20 19:11 UTC
Labels: enhancement
