### ISSUE TITLE
Properly document ale_virtualtext_cursor to the project README so users can find it

### ISSUE THREAD

**Issue by zakkudo** [dense-analysis/ale#4468] opened 2023-03-07 02:01 UTC
There are going to be a lot of bugs created by the hidden configuration for turning virtual text off.  It needs to be added to the README of the project.

'''
let ale_virtualtext_cursor = 'disabled'
'''

If this isn't possible, the project should recommend that it only takes one line to install YouCompleteMe.  Many of us have built a workflow around how ALE works, and we don't have time to be searching the whole source code if the project if something breaks it.  We make a living using tools like this and the change wasn't mean ruined anywhere meaningful.

**Comment by zakkudo** [comment] 2023-03-07 02:04
Literally, some of us either had to switch to something else or use nothing at all if we couldn't find this config so we can feed our families.

**Comment by w0rp** [comment] 2023-03-07 02:12
Duplicate of #4441.

**Closed by w0rp** 2023-03-07 02:12 UTC
Labels: enhancement

**Comment by coolaj86** [comment] 2023-03-07 23:19
@zakkudo If you install via https://webinstall.dev/vim-ale it will clone this official git repo and then add this very light config file with reasonable defaults, including changing that option to be a single line:

https://github.com/webinstall/webi-installers/blob/main/vim-ale/ale.vim

```vim
" turn on the syntax checker
syntax on

" don't check immediately on open (or quit)
let g:ale_lint_on_enter = 0
" check on save
let g:ale_lint_on_save = 1

" don't spam the virtual text ('disable' to disable)
let g:ale_virtualtext_cursor = 'current'

" These emojis go in the sidebar for errors and warnings
" other considerations: '💥' '☢️' '⚡' '☠' '●' '.'
" Note: one- and two-byte characters are more compatible
let g:ale_sign_error = '✘'
let g:ale_sign_warning = '⚠️'

" show error count
function! LinterStatus() abort
    let l:counts = ale#statusline#Count(bufnr(''))
    let l:all_errors = l:counts.error + l:counts.style_error
    let l:all_non_errors = l:counts.total - l:all_errors
    return l:counts.total == 0 ? 'OK' : printf(
        \   '%d⨉ %d⚠ ',
        \   all_non_errors,
        \   all_errors
        \)
endfunction
set statusline+=%=
set statusline+=\ %{LinterStatus()}

" how to show error message
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
```
